### ISSUE TITLE
No error but image is not saved in ios10 phone gallery

### ISSUE THREAD

**Issue by kby799** [Nexxa/cordova-base64-to-gallery#12]
> Installed platforms:
>   android 4.1.1
>   ios 4.1.1
> 
> Cordova CLI: 6.3.1
> Gulp version:  CLI version 3.9.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 1.3.1
> Ionic CLI Version: 2.1.0
> Ionic App Lib Version: 2.0.0-beta.20
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v4.6.0
> Xcode version: Xcode 8.0 Build version 8A218a 

The path that is show in the callback function
../Library/NoCloud/S408920411140.png

> cordova-base64-to-gallery 4.1.1 "base64ToGallery"

Played around with the CSP meta-tag, but it doesn't fix and change anything. Not sure where to go from here, please help.

**Comment by kby799** [comment]
Very silly of me, should have read the xcode console. It looks like there is a permission problem. 

> This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by StefanoMagrassi** [comment]
@kby799 the new iOS 10 privacy policies became more restrictive and now force you to add a description to some fields in the `*-Info.plist` file.

It's a little bit boring to keep this fields up-to-date, especially because cordova builds can delete/override them.
I suggest you to try [this plugin](https://github.com/dpa99c/cordova-custom-config) (or something similar).
