### ISSUE TITLE
How do i implement this in a service, using Ionic 1?

### ISSUE THREAD

**Issue by FredrikHa** [Nexxa/cordova-base64-to-gallery#13]
An example :-)

**Comment by yelhouti** [comment]
use ionic native, it's in there

**Comment by StefanoMagrassi** [comment]
@FredrikHa you don't need any Ionic-specific code, just Angular.

Take a look at the [gist I wrote](https://gist.github.com/StefanoMagrassi/8103b535000ff144d6b07919a4bb61f0).
It is a simple factory (I prefer factories instead of services) that exposes a "save" method to which you can pass base64 string as parameter.
The factory returns a Promise which is resolved, if the plugin returns a result, or rejected, if the plugin returns an error.
