### ISSUE TITLE
TypeError: undefined is not an object (evaluating 's[t].apply'

### ISSUE THREAD

**Issue by shohoku11wrj** [Nexxa/cordova-base64-to-gallery#17]
When I was invoking Base64ToGallery.base64ToGallery(...) function as described on official document: http://ionicframework.com/docs/v2/native/base64-to%20gallery/ ,
There is an error thrown:

The log:
**Feb  5 19:33:55 xxxx-MAC-2 xxxxx[17446]: Error saving image to gallery  TypeError: undefined is not an object (evaluating 's[t].apply')**

My testing data is hard coded a dataUrl string.

My running environment is:
cordova platform ios 4.0.0
ionic 2.1.17
on a simulator of iPhone6.0 with iOS 10.2

Anyone has had this problem?

**Comment by shohoku11wrj** [comment]
I was able to solve the previous issue by running `ionic plugin add cordova-base64-to-gallery`, and also re-installed the cordova ios platform by `cordova platform add ios --variable NSPhotoLibraryUsageDescription="Privacy - Photo Library Usage Description" --save`.

However, the app does not download my image with the dataURL.

**Comment by StefanoMagrassi** [comment]
@shohoku11wrj I'm sorry but, as you can see in the [readme](https://github.com/Nexxa/cordova-base64-to-gallery/blob/master/README.md), the project is discontinued since the begininning of the year.

We didn't even know that the Ionic team added our package, which is a simple Cordova plugin, to the ionic-native bundle - or at least into the official documentation.

You can fork the repo and try to fix the bug by yourself or open an issue on the ionic-native repository in order to warn them.

**Comment by shohoku11wrj** [comment]
@StefanoMagrassi Thanks for the feedback. I will try some way else.
