### ISSUE TITLE
Could you add an Option for not using the Media-Scanner

### ISSUE THREAD

**Issue by bastian-meier** [Nexxa/cordova-base64-to-gallery#4]
Hello,

thanks for your great plugin. Is there a way to not trigger the Media-Scanner after creating the image.
In my App i move the File in a special Folder, but in the Android-Galery the Folder "Pictures" shows on Image (it shows grey because it is not there anymore)

Would be great if you could implement a option to not trigger the Media-Scanner.

Thanks
Bastian

**Comment by StefanoMagrassi** [comment]
Hi @bastian-meier 

I can add an option to disable the Media-Scanner, but with the current implementation the "Pictures" folder will be still created (both on Android, iOS and WP).

It would be extremely more useful to have the possibility to choose the destination directory on cordova/javascript side, but I'm not a java/objective-c/c# developer and I would need some extra-time (which I completely lack now...) to implement this feature...

**Comment by StefanoMagrassi** [comment]
@bastian-meier I pushed a new branch ([issue#4](https://github.com/Nexxa/cordova-base64-to-gallery/tree/issue%234)) with the changes to enable/disable Media-Scanner on Android.

I also changed the api on javascript/cordova side, so please take a look to the new README.

Please, try and test it and if it is ok I'll merge the issue branch into master and republish the plugin.
In order to test this version, I suggest you to clone the repository, move to issue#4 branch and temporarily add the local version of the plugin to your application:

``` shell
cd <PATH_TO_YOUR_PROJECT>
cordova plugin rm cordova-base64-to-gallery
cordova plugin add <PATH_TO_LOCAL_REPOSITORY>
```

see [cordova docs](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#plugin-spec)

**Comment by bastian-meier** [comment]
@StefanoMagrassi thanks for your work.

there was a 'incompatible types'-bug with the boolean mediaScannerEnabled variable.

I fixed it, tested it and created a pull-request #5

**Comment by StefanoMagrassi** [comment]
@bastian-meier I saw your PR: ok for the bug in java class, but the solution on js side doesn't convince me.

The API signature, imho, has to be as cleaner as possible, so it must permit only one type of parameter and the options object solution it's the most flexible one.
Furthermore, my implementation wanted to be more functional and lesser imperative...

So, recap:
:+1:  bug fix on Android
:+1:  media scanner option in camel case
:-1:  two types of parameters

**Comment by StefanoMagrassi** [comment]
@bastian-meier if you want, you can send a new PR with only the "ok" changes or I can cherry-pick and push them to the repository.

**Comment by bastian-meier** [comment]
@StefanoMagrassi 

I just updated the PR, you are right with the API ... it is much better with a needed options object.

**Comment by bastian-meier** [comment]
@StefanoMagrassi  if you dont like my "if typeof options.xxx !== 'undefinded'" - solution for setting defaults, its also OK for me when you cherry-pick the changes you like :-)

**Comment by StefanoMagrassi** [comment]
@bastian-meier it's better to not fill the code with this static controls: it's more difficult to maintain and it's less flexible.

I will cherry-pick the commits and push a new version in this branch. Then, if it's ok, I'll prepare a new release

**Comment by StefanoMagrassi** [comment]
@bastian-meier I pushed the changes.

Please test it just an other time

**Comment by bastian-meier** [comment]
I am getting a error:
`Uncaught module object.assign not found`

I dont have object.assign installed in my project and it should not be a dependencie, what do you think?
Imho using a ployfill and 3 extra functions is not easier to maintain then this 2 lines of code:

`var prefix = options.prefix === undefined ? 'img_' : options.prefix,`
`mediaScanner = options.mediaScanner === undefined ? true: options.mediaScanner;`

**Comment by StefanoMagrassi** [comment]
The 3 extra functions are pure (same inputs give back same outputs) and abstract.
The 2 lines of code are specific and static.

If in the future we'll add some other option, we'll need to add more lines.

You had this issue with object.assign because you didn't run "npm update": when the plugin will be published, this step will be done under the hood.
Because the plugin still supports nodejs 0.12 I had to use the object.assign polyfill package, otherwise in order to elegantly merge objects I'd have to add some bigger library like underscore or lodash or whatever.

The real issue is that it would be better to directly pass the options object to the Android/iOS/WP layer, but I'm not a java/objective-c/c# developer and I have no time to try...

**Comment by StefanoMagrassi** [comment]
I would agree to temporarily leave the 2 lines of code if someone starts to work on the platforms side

**Comment by bastian-meier** [comment]
because i use phonegap build with the git url as plugin spec i could not load dependency.

check my last commit [link](https://github.com/bastian-meier/cordova-base64-to-gallery/commit/79e4a3b604ef1439b82f87a25791284fb3fd75e9#diff-aa8ed3b984fc6bb9c35ce0f283d5c85b) for my 'non static' solution without the dependency.

**Comment by StefanoMagrassi** [comment]
Uhm, there are 2 problems with that solution:
- the order of object properties isn't guarantee and we need that the arguments array has values in the right order;
- the extra properties in the options object are ignored; this is not an overall good or bad thing, but it would restrict the possibility to pass extra "optional" parameters.

I think that a median way to solve the problem it to remove the external dependencies and use a project-specific version of the polyfill.

I will update the branch in minutes

**Comment by StefanoMagrassi** [comment]
@bastian-meier please check it now.

**Comment by bastian-meier** [comment]
build works fine, but i get this error at app-start:

`Uncaught module cordova-base64-to-gallery./lib/object.assign-polyfill not found`

I dont know much about cordova plugins, but i think alls js has to be in www folder !?

**Comment by StefanoMagrassi** [comment]
Too cool to be real... Cordova doesn't transpile commonjs to standard javascript... So requiring doesn't work out of the box, without a "build" phase using browserify or tools like that...

Nice solution: add the above-mentioned build phase and prepare a pre-publish script in order to automatically publish the plugin with source and dist code.

Ugly solution: put the polifyll in the js file under www ...

@bastian-meier  If you can wait untill tomorrow I will go with the nice solution. Otherwise I can implement the "bad" one in few minutes

p.s.: sorry if I used you as a tester, but it is faster then create a simple testing app from scratch

**Comment by bastian-meier** [comment]
no problem,

i think i can wait for the nice solution, i use my own branch at the moment.
But i am looking forward to use your Version :-)

**Comment by StefanoMagrassi** [comment]
:wink:

**Comment by StefanoMagrassi** [comment]
Ok, after some "treasure hunting" I found [this](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#js-module) and I understood that an external file has to be added in plugin.xml in order to be required in the main plugin js...

I pushed the changes and I think it will work fine. Please, @bastian-meier  test it

**Comment by bastian-meier** [comment]
Works like a Charm! Thank you!

**Comment by StefanoMagrassi** [comment]
Goooood! Now I merge the issue branch into master and publish the new version

**Comment by StefanoMagrassi** [comment]
New version 4.0.0 published on cordova registry
